version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - 5432:5432
    volumes:
        - db:/var/lib/postgresql/data
volumes:
  db: